---

- name: restart cockpit
  service:
    name: cockpit.service
    state: restarted
  when: restart_cockpit

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart sssd
  service:
    name: sssd
    state: restarted
